//! # Causal Set Spectral Dimension Engine
//!
//! Implements the Kuratowski Calculus from Fractal Entropic Geometrodynamics (FEG).
//!
//! ## Theory
//!
//! Spacetime is modelled as a locally finite partially ordered set (causal set),
//! generated by Poisson sprinkling into a 4D causal diamond. The partial order
//! encodes causal structure: event A ≺ B means A can causally influence B.
//!
//! The Hasse diagram (transitive reduction) retains only nearest-neighbor causal
//! links, discarding redundant long-range edges. On this skeleton:
//!
//! - **Matter** emerges as Causal Prisms (K₂,ₙ bipartite structures with 2 poles
//!   and N ≥ 3 intermediate nodes). These are topological defects that anchor
//!   probability flow and define particle-like spectral signatures. Mass = N.
//!
//! - **The Strong Force** operates through K₅ threat detection and vertex
//!   contraction. When a threat node connects to both poles and ≥2 intermediates
//!   of a Causal Prism, it is absorbed into the nearest pole — a discrete
//!   analogue of colour confinement preserving planarity.
//!
//! - **Gravity** is the spectral dimension d_S(t) = −2 d(ln P)/d(ln t),
//!   measured via undirected random walkers on the Hasse graph.
//!   The vacuum spectral dimension reflects the geometry of empty spacetime;
//!   the defect spectral dimension reveals how matter modifies geometry.
//!
//! - **Electromagnetism** is causal flux: directed walkers following the
//!   arrow of time, measuring transmission probability between particle
//!   generations (attraction) and within the same generation (repulsion).
//!
//! ## Phases
//!
//! | Phase | Module | Physics |
//! |-------|--------|---------|
//! | 1 | [`diamond`] | Vacuum generation: Poisson sprinkling + Hasse diagram |
//! | 2 | [`skyrmion`] | Kuratowski contraction: Causal Prism detection + K₅ absorption |
//! | 3 | [`spectral`] | Spectral dimension: random walk return probability |
//! | — | [`anim_export`] | Binary topology slice export for external renderers |
//! | 4 | [`output`] | CSV serialisation of ensemble-averaged observables |
//!
//! ## Data Flow
//!
//! ```text
//! sprinkle(N) → [f64;4] points
//!     ↓
//! build_hasse() → CSR adjacency (adj_head, adj_data) + bulk_momentum
//!     ↓                [3 termination valves: degree cap, Alexandrov short-circuit, dry-shell]
//! apply_defect() → Causal Prisms, K₅ threat absorption, generation classification
//!     ↓                [minimum valence pruning: skip nodes with degree < 3]
//!     +--[--export-slice]-→ write_slice() → .slice file (bincode, early exit)
//!     ↓
//! run_walkers() → P(t), d_S(t) for vacuum/defect/generations/flux
//!     ↓                [u64 integer accumulation; f64 only at final division]
//! write_csv() → results.csv
//! ```

pub mod anim_export;
pub mod checkpoint;
pub mod diamond;
pub mod memory;
pub mod output;
pub mod skyrmion;
pub mod spectral;
