#!/usr/bin/env python3
r"""
Corrected Skyrmion Mass Ratio Scan (v03) for "Modulo Synthesis"
=============================================================================
PHYSICS THEORETICAL BASIS:
1.  **Causal Set Theory**: Spacetime is discrete and generated by Poisson sprinkling, 
    preserving Lorentz invariance stochastically (Bombelli, Sorkin).
2.  **Modulo Synthesis**: Particles are field excitations on this discrete geometry.
    - **Baryons (Skyrmions)**: Topological solitons ($B=1$) where the SU(2) field wraps 
      the spatial $S^3$. This topology protects them from decay (Proton stability).
    - **Leptons (Wavepackets)**: Non-topological excitations ($B=0$) or "ripples" in the 
      phase field. They lack the topological knot and thus have much lower mass.
3.  **Mass Ratio**: The physical observable is the ratio of the energy cost of the 
    topological knot (Baryon) to the energy cost of a minimal quantum ripple (Lepton).
    $$ Ratio = \frac{E_{soliton} - E_{vac}}{E_{ripple} - E_{vac}} $$
4.  **Correlated Noise**: In a discrete stochastic vacuum, "zero" energy is defined by 
    the vacuum noise floor. To detect small excitations (Leptons), we must subtract 
    the *exact same* vacuum realization from both signal+noise and noise-only states.
=============================================================================
"""

import argparse
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import cKDTree
from numba import jit, prange
from tqdm import tqdm
import time

np.random.seed(42)

# =============================================================================
# SU(2) utilities
# =============================================================================

@jit(nopython=True, cache=True)
def trace_diff(U1, U2):
    r"""
    Computes the Kinetic Energy density (Tr|d U|^2).
    In the continuum limit, this becomes $\partial_\mu U \partial^\mu U^\dagger$.
    On a Causal Set, this measures the "smoothness" of the field between connected events.
    """
    diff = U2 - U1
    return (diff[0,0].real**2 + diff[0,0].imag**2 +
            diff[0,1].real**2 + diff[0,1].imag**2 +
            diff[1,0].real**2 + diff[1,0].imag**2 +
            diff[1,1].real**2 + diff[1,1].imag**2)

@jit(nopython=True, cache=True)
def trace_commutator(U1, U2):
    r"""
    Computes the Skyrme Term (Quartic interaction).
    In continuum: $Tr([L_\mu, L_\nu]^2)$.
    This term provides the repulsive pressure that stabilizes the Skyrmion against shrinking 
    (Derrick's Theorem). On a discrete set, it arises from the non-commutativity of 
    field differences across minimal 3-simplices.
    """
    comm00 = U1[0,0]*U2[0,0] + U1[0,1]*U2[1,0] - U2[0,0]*U1[0,0] - U2[0,1]*U1[1,0]
    comm01 = U1[0,0]*U2[0,1] + U1[0,1]*U2[1,1] - U2[0,0]*U1[0,1] - U2[0,1]*U1[1,1]
    comm10 = U1[1,0]*U2[0,0] + U1[1,1]*U2[1,0] - U2[1,0]*U1[0,0] - U2[1,1]*U1[1,0]
    comm11 = U1[1,0]*U2[0,1] + U1[1,1]*U2[1,1] - U2[1,0]*U1[0,1] - U2[1,1]*U1[1,1]
    return (comm00.real**2 + comm00.imag**2 +
            comm01.real**2 + comm01.imag**2 +
            comm10.real**2 + comm10.imag**2 +
            comm11.real**2 + comm11.imag**2)

@jit(nopython=True, cache=True)
def su2_from_hedgehog(F, r_hat):
    r"""
    Constructs an SU(2) matrix from the "Hedgehog" ansatz.
    The field points radially outward in isospace, governed by profile F(r).
    $U(\vec{r}) = \exp(i F(r) \hat{r} \cdot \vec{\sigma})$
    """
    cosF = np.cos(F)
    sinF = np.sin(F)
    rx, ry, rz = r_hat
    U = np.zeros((2, 2), dtype=np.complex128)
    U[0,0] = cosF + 1j * sinF * rz
    U[0,1] = 1j * sinF * (rx - 1j*ry)
    U[1,0] = 1j * sinF * (rx + 1j*ry)
    U[1,1] = cosF - 1j * sinF * rz
    return U

# =============================================================================
# Causal set generation
# =============================================================================

def generate_causal_set(N=20000, radius=8.0):
    """
    Generates a Causal Set via Poisson Sprinkling into Minkowski space.
    This preserves Lorentz invariance (unlike a lattice grid).
    The points represent spacetime "atoms" or events.
    """
    points = []
    while len(points) < N:
        p = np.random.uniform(-radius, radius, (10000, 4))
        r = np.sqrt(np.sum(p[:,1:]**2, axis=1))
        inside = (r < radius) & (p[:,0] > 0)
        points.append(p[inside])
    points = np.vstack(points)[:N].astype(np.float64)
    # Sort by time to establish causal order (t_i < t_j implies potential link)
    points = points[np.argsort(points[:,0])]
    # Use KDTree for efficient spatial neighbor lookup (essential for T480 performance)
    tree = cKDTree(points[:,1:])
    return points, tree

# =============================================================================
# Field generation (JIT optimized)
# =============================================================================

@jit(nopython=True, cache=True, parallel=True)
def hedgehog_field(points, lambda_decay):
    """
    Generates a Baryon (Skyrmion) configuration.
    Topology: B = 1.
    Boundary Conditions: F(0) = pi, F(inf) = 0.
    This "twist" creates a stable particle-like soliton.
    """
    N = len(points)
    U = np.zeros((N, 2, 2), dtype=np.complex128)
    PI = np.pi
    
    for i in prange(N):
        rx = points[i, 1]
        ry = points[i, 2]
        rz = points[i, 3]
        r_sq = rx*rx + ry*ry + rz*rz
        r_norm = np.sqrt(r_sq)
        if r_norm < 1e-9:
            r_norm = 1e-9
            
        # Profile F(r) decays exponentially from PI to 0
        F = PI * np.exp(-r_norm / lambda_decay)
        
        cosF = np.cos(F)
        sinF = np.sin(F)
        
        # r_hat director
        nx = rx / r_norm
        ny = ry / r_norm
        nz = rz / r_norm
        
        U[i,0,0] = cosF + 1j * sinF * nz
        U[i,0,1] = 1j * sinF * (nx - 1j*ny)
        U[i,1,0] = 1j * sinF * (nx + 1j*ny)
        U[i,1,1] = cosF - 1j * sinF * nz
        
    return U

@jit(nopython=True, cache=True, parallel=True)
def trivial_wavepacket(points, lambda_decay, amplitude):
    """
    Generates a Lepton configuration (Minimal Ripple).
    Topology: B = 0.
    This is a "fake knot" or "bump" in phase that has energy but no topological stability.
    It represents a fundamental quantum excitation (Lepton) used as a mass reference.
    Amplitude should be small (~vacuum fluctuation level) to represent a quantum ripple.
    """
    N = len(points)
    U = np.zeros((N, 2, 2), dtype=np.complex128)
    
    for i in prange(N):
        rx = points[i, 1]
        ry = points[i, 2]
        rz = points[i, 3]
        r_norm = np.sqrt(rx*rx + ry*ry + rz*rz)
        if r_norm < 1e-9:
            r_norm = 1e-9
            
        # Simple Gaussian phase bump (non-topological)
        phase = amplitude * np.exp(-r_norm / lambda_decay)
        c = np.cos(phase)
        s = np.sin(phase)
        
        U[i,0,0] = c + 1j * s
        U[i,1,1] = c - 1j * s
        # Off-diagonals are 0 (Abelian-like structure locally)
        
    return U

@jit(nopython=True, cache=True, parallel=True)
def zero_mode_field(N, amplitude):
    """
    Generates Vacuum Noise (Zero Mode).
    Corresponds to the quantum foam or vacuum expectation value (VEV) fluctuations.
    """
    U = np.zeros((N, 2, 2), dtype=np.complex128)
    for i in prange(N):
        phase = np.random.uniform(-amplitude, amplitude)
        c = np.cos(phase)
        s = np.sin(phase)
        U[i,0,0] = c + 1j * s
        U[i,1,1] = c - 1j * s
        
    return U
    
@jit(nopython=True, cache=True, parallel=True)
def multiply_fields(U_in, U_noise):
    """
    Composes a physical field with the vacuum noise.
    Mathematically: U_total(x) = U_matter(x) * U_vacuum(x)
    This "dresses" the bare Skyrmion/Lepton with the local vacuum fluctuations.
    """
    N = len(U_in)
    U_out = np.empty_like(U_in)
    
    for i in prange(N):
        # Matrix multiplication to combine rotations
        u00 = U_in[i,0,0]
        u01 = U_in[i,0,1]
        u10 = U_in[i,1,0]
        u11 = U_in[i,1,1]
        
        n00 = U_noise[i,0,0]
        n01 = U_noise[i,0,1]
        n10 = U_noise[i,1,0]
        n11 = U_noise[i,1,1]
        
        U_out[i,0,0] = u00*n00 + u01*n10
        U_out[i,0,1] = u00*n01 + u01*n11
        U_out[i,1,0] = u10*n00 + u11*n10
        U_out[i,1,1] = u10*n01 + u11*n11
        
    return U_out

# =============================================================================
# Energy computation (k-NN version)
# =============================================================================

@jit(nopython=True, cache=True, parallel=True)
def compute_energy_kNN(points, U_field, nbr_indices, nbr_offsets):
    """
    Calculates the Total Energy (Hamiltonian) of the field configuration via k-NN.
    
    Physical Motivation:
    - On a Causal Set, derivatives are finite differences between connected events.
    - We use k-Nearest Neighbors (k-NN) in the embedding space to approximate these
      local connections, which is efficient and preserves statistical Lorentz invariance.
    - Energy = Kinetic (smoothness) + Skyrme (stability/stiffness).
    """
    N = len(points)
    kinetic = 0.0
    quartic = 0.0
    total_links = 0
    
    for i in prange(N):
        ti = points[i, 0]
        xi0 = points[i, 1]
        xi1 = points[i, 2]
        xi2 = points[i, 3]
        
        U_i_00 = U_field[i,0,0]
        U_i_01 = U_field[i,0,1]
        U_i_10 = U_field[i,1,0]
        U_i_11 = U_field[i,1,1]
        
        local_kin = 0.0
        local_qrt = 0.0
        local_links = 0
        
        start = nbr_offsets[i]
        end = nbr_offsets[i+1]

        for idx in range(start, end):
            j = nbr_indices[idx]
            if j <= i: continue # Avoid double counting
            
            tj = points[j, 0]
            dt = tj - ti
            if dt <= 0: continue # Causality: only link to future (or past)
            
            dx = points[j,1] - xi0
            dy = points[j,2] - xi1
            dz = points[j,3] - xi2
            dist_sq = dx*dx + dy*dy + dz*dz
            
            if dist_sq >= dt*dt: continue # Lightcone check: must be timelike
            
            U_j_00 = U_field[j,0,0]
            U_j_01 = U_field[j,0,1]
            U_j_10 = U_field[j,1,0]
            U_j_11 = U_field[j,1,1]
            
            # 1. Kinetic Term (Dirichlet energy ~ |dU|^2)
            d00 = U_j_00 - U_i_00
            d01 = U_j_01 - U_i_01
            d10 = U_j_10 - U_i_10
            d11 = U_j_11 - U_i_11
            
            tr_diff = (d00.real**2 + d00.imag**2 +
                       d01.real**2 + d01.imag**2 +
                       d10.real**2 + d10.imag**2 +
                       d11.real**2 + d11.imag**2)
            
            local_kin += tr_diff / (dt * dt)
            
            # 2. Skyrme Term (Commutator ~ [L,R]^2)
            comm00 = U_i_00*U_j_00 + U_i_01*U_j_10 - U_j_00*U_i_00 - U_j_01*U_i_10
            comm01 = U_i_00*U_j_01 + U_i_01*U_j_11 - U_j_00*U_i_01 - U_j_01*U_i_11
            comm10 = U_i_10*U_j_00 + U_i_11*U_j_10 - U_j_10*U_i_00 - U_j_11*U_i_10
            comm11 = U_i_10*U_j_01 + U_i_11*U_j_11 - U_j_10*U_i_01 - U_j_11*U_i_11
            
            tr_comm = (comm00.real**2 + comm00.imag**2 +
                       comm01.real**2 + comm01.imag**2 +
                       comm10.real**2 + comm10.imag**2 +
                       comm11.real**2 + comm11.imag**2)
            
            local_qrt += tr_comm
            local_links += 1

        kinetic += local_kin
        quartic += local_qrt
        total_links += local_links

    return kinetic + quartic, total_links

# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Skyrmion Mass Ratio Scanner (v03)")
    parser.add_argument("-n", "--nodes", type=int, default=50000, help="Number of Causal Set events (Hard-limited for T480 safety)")
    parser.add_argument("--k-neighbors", type=int, default=16, help="k-NN count for finite-difference approximation")
    parser.add_argument("--fluct", type=float, default=0.0174, help="Vacuum fluctuation scale (Noise floor)")
    parser.add_argument("--lambda-single", type=float, default=0.31, help="Core size (decay length) of the Skyrmion")
    parser.add_argument("--runs", type=int, default=3, help="Number of statistical runs")
    parser.add_argument("--lepton-amp", type=float, default=-1.0, help="Amplitude for Lepton field (<0 means sqrt(fluct))")
    args = parser.parse_args()

    # T480 SANITIZATION: Prevent memory explosion
    N = min(args.nodes, 50000)
    if args.nodes > 50000:
        print(f"Warning: N limited to 50000 for T480 performance safety.")
    
    k_neighbors = args.k_neighbors
    fluct = args.fluct
    ld = args.lambda_single
    runs = args.runs
    
    # Physics Decision: Lepton Amplitude
    # To be a valid quantum reference mass, the Lepton must be a "minimal excitation".
    # We use sqrt(fluct) to ensure the signal power (~amp^2) rises above the vacuum variance (~fluct).
    if args.lepton_amp < 0:
        lep_amp = np.sqrt(fluct)
        print(f"Physics Config: Lepton Amplitude = {lep_amp:.4f} (Derived from sqrt(fluct) for S/N stability)")
    else:
        lep_amp = args.lepton_amp
        print(f"Physics Config: Lepton Amplitude = {lep_amp} (User Override)")

    print(f"Simulation Params: λ={ld:.3f}, N={N}, k={k_neighbors}, Vacuum Noise={fluct}")

    # 1. Generate Geometry
    print("Generating discrete spacetime (Causal Set)...")
    points, tree = generate_causal_set(N=N, radius=8.0)

    # 2. Build Connectivity (Lorentz-invariant k-NN)
    _, nbr_indices = tree.query(points[:,1:], k=k_neighbors)
    nbr_indices = nbr_indices.flatten()
    nbr_offsets = np.arange(0, len(nbr_indices)+1, k_neighbors, dtype=np.int64)

    ratios = []
    bar_masses = []
    lep_masses = []
    
    # JIT Compile Warmup
    print("Compiling Physics Kernels (JIT)...")
    dummy_points = points[:100]
    dummy_indices = np.zeros(100*k_neighbors, dtype=np.int64)
    dummy_offsets = np.arange(0, 100*k_neighbors+1, k_neighbors, dtype=np.int64)
    _ = hedgehog_field(dummy_points, 1.0)
    _ = trivial_wavepacket(dummy_points, 1.0, 1.0)
    _ = zero_mode_field(100, 0.1)
    _ = multiply_fields(np.zeros((100,2,2), dtype=np.complex128), np.zeros((100,2,2), dtype=np.complex128))
    _ = compute_energy_kNN(dummy_points, np.zeros((100,2,2), dtype=np.complex128), dummy_indices, dummy_offsets)
    print("Physics Ready.")

    for run in range(runs):
        # -------------------------------------------------------------------------
        # PHYSICAL MASS CALCULATION
        # -------------------------------------------------------------------------
        # Crucial Step: Correlated Noise Subtraction
        # We generate a SINGLE realization of vacuum noise (U_noise).
        # We assume Physics = Signal * Noise.
        # Mass = E(Signal * Noise) - E(Identity * Noise).
        # This correlation cancels the O(1) vacuum energy, leaving the O(signal) mass.
        # -------------------------------------------------------------------------
        
        U_noise = zero_mode_field(N, fluct) 
        U_vac = U_noise 

        # Generate "Bare" Particles
        U_smooth_bar = hedgehog_field(points, ld)                  # Baryon: Topological (Knot)
        U_smooth_lep = trivial_wavepacket(points, ld, amplitude=lep_amp) # Lepton: Non-topological (Ripple)

        # "Dress" Particles with Vacuum Noise
        U_baryon = multiply_fields(U_smooth_bar, U_noise)
        U_lepton = multiply_fields(U_smooth_lep, U_noise)

        # Compute Energies (Hamiltonians)
        E_vac, _ = compute_energy_kNN(points, U_vac, nbr_indices, nbr_offsets)
        E_bar, _ = compute_energy_kNN(points, U_baryon, nbr_indices, nbr_offsets)
        E_lep, _ = compute_energy_kNN(points, U_lepton, nbr_indices, nbr_offsets)

        # Mass = Energy above Vacuum
        Mass_Baryon = E_bar - E_vac
        Mass_Lepton = E_lep - E_vac
        
        # Calculate Ratio
        if Mass_Lepton < 1e-12:
             ratio = np.nan # Avoid division by zero if signal lost in noise
        else:
             ratio = Mass_Baryon / Mass_Lepton

        ratios.append(ratio)
        bar_masses.append(Mass_Baryon)
        lep_masses.append(Mass_Lepton)
        print(f"  Run {run+1}/{runs}: M_bar={Mass_Baryon:.2e} M_lep={Mass_Lepton:.2e} -> ratio = {ratio:.1f}x")

    mean_ratio = np.nanmean(ratios)
    std_ratio = np.nanstd(ratios)
    
    mean_bar = np.nanmean(bar_masses)
    std_bar = np.nanstd(bar_masses)
    mean_lep = np.nanmean(lep_masses)
    std_lep = np.nanstd(lep_masses)

    print(f"\nFINAL RESULT: λ_decay = {ld:.3f} → Ratio = {mean_ratio:.1f} ± {std_ratio:.1f}x")
    print(f"  Baryon Mass = {mean_bar:.2e} ± {std_bar:.2e}")
    print(f"  Lepton Mass = {mean_lep:.2e} ± {std_lep:.2e}")
    print("Scan complete.")
